export type PropertyUse = "investment" | "ppor";
export type PurchaseMode = "new" | "existing";
export type LoanType = "principal-interest" | "interest-only";
export type ViewMode = "summary" | "property" | "tax" | "equity" | "deductions";

export interface YearData {
  year: number;
  propertyValue: number;
  loanBalance: number;
  equity: number;
  rentalIncome: number;
  vacancy: number;
  managementFee: number;
  netRentalIncome: number;
  loanRepayment: number;
  interestPortion: number;
  principalPortion: number;
  councilRates: number;
  waterRates: number;
  insurance: number;
  maintenance: number;
  strataFees: number;
  totalExpenses: number;
  preTaxCashflow: number;
  depDiv43: number;
  depDiv40: number;
  otherDeductibles: number;
  totalDeductions: number;
  rentalLossOrGain: number;
  taxBenefit: number;
  afterTaxCashflow: number;
  salary: number;
  otherIncome: number;
  ongoingCosts: number;
  gearing: number;
  totalIncomeAll: number;
  totalDeductionsForTax: number;
  taxableIncomeCalc: number;
  incomeTaxCalc: number;
  incomeTaxWithout: number;
  taxSaved: number;
  grossIncome: number;
  afterTaxIncome: number;
  cfTotalIncome: number;
  netCashflow: number;
  propertyCashflow: number;
  offsetBalanceAtYear: number;
  propertyEquity: number;
  netEquity: number;
}
